name: test-action-javascript
on: push
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Cryptosoft-SBOM-generator.
        id: Cryptosoft-SBOM-generator
        uses: CryptosoftInc/Dependency-Track@1.0.0
        with:
          dt-url:  "https://dt-api-kkloeckner-llc.staging.cryptosoft.com/api/v1/bom"
          api-key: 'yx2ZOrANGcuYonKkkeXcOQp77xT2XqvA '
          project-name: "Testproject2"
          project-version: "1.0"
